// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teamframe/EmployeesDenseTable.tsx": () => import("../components/mockups/teamframe/EmployeesDenseTable.tsx"),
  "./components/mockups/teamframe/EmployeesRichGrid.tsx": () => import("../components/mockups/teamframe/EmployeesRichGrid.tsx"),
  "./components/mockups/teamframe/EmployeesStatusGrouped.tsx": () => import("../components/mockups/teamframe/EmployeesStatusGrouped.tsx"),
  "./components/mockups/teamframe/TeamFrame.tsx": () => import("../components/mockups/teamframe/TeamFrame.tsx")
};
