// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teamframe/AppShell.tsx": () => import("../components/mockups/teamframe/AppShell.tsx"),
  "./components/mockups/teamframe/DarkToast.tsx": () => import("../components/mockups/teamframe/DarkToast.tsx"),
  "./components/mockups/teamframe/DrillDownPanel.tsx": () => import("../components/mockups/teamframe/DrillDownPanel.tsx"),
  "./components/mockups/teamframe/EmployeesDenseTable.tsx": () => import("../components/mockups/teamframe/EmployeesDenseTable.tsx"),
  "./components/mockups/teamframe/EmployeesRichGrid.tsx": () => import("../components/mockups/teamframe/EmployeesRichGrid.tsx"),
  "./components/mockups/teamframe/EmployeesStatusGrouped.tsx": () => import("../components/mockups/teamframe/EmployeesStatusGrouped.tsx"),
  "./components/mockups/teamframe/EmptyOrgGuide.tsx": () => import("../components/mockups/teamframe/EmptyOrgGuide.tsx"),
  "./components/mockups/teamframe/LoadingScreen.tsx": () => import("../components/mockups/teamframe/LoadingScreen.tsx"),
  "./components/mockups/teamframe/OrgHealthSummary.tsx": () => import("../components/mockups/teamframe/OrgHealthSummary.tsx"),
  "./components/mockups/teamframe/OrgReadyBanner.tsx": () => import("../components/mockups/teamframe/OrgReadyBanner.tsx"),
  "./components/mockups/teamframe/PrimaryButton.tsx": () => import("../components/mockups/teamframe/PrimaryButton.tsx"),
  "./components/mockups/teamframe/SetupProgressCard.tsx": () => import("../components/mockups/teamframe/SetupProgressCard.tsx"),
  "./components/mockups/teamframe/TeamFrame.tsx": () => import("../components/mockups/teamframe/TeamFrame.tsx")
};
